language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.3.1
  - DJANGO_VERSION=1.4
# command to install dependencies
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r .requirements.txt
  - python setup.py develop
# command to run tests
script: python runtests.py